function createfigure1(X1, Y1)
%CREATEFIGURE1(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 24-May-2017 15:36:50

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'MarkerFaceColor',[0 0 1],...
    'MarkerEdgeColor',[0.929411768913269 0.694117665290833 0.125490203499794],...
    'MarkerSize',8,...
    'Marker','o',...
    'LineWidth',3,...
    'Color',[0.501960813999176 0.501960813999176 0.501960813999176]);

% Create xlabel
xlabel('log10 concentration (micromolar)');

% Create ylabel
ylabel('% Response');

box(axes1,'on');
